### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by safezpa** [hiromaily/go-gin-wrapper#1]
when I exec /go/bin/ginserver -f ./data/toml/docker.toml the follow error ocurs:

17:34:29 app         | panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x551066]

17:34:29 app         | goroutine 1 [running]:
crypto/cipher.NewCBCDecrypter(0x0, 0x0, 0x0, 0x0, 0x0, 0x50, 0x0)
        /usr/local/go/src/crypto/cipher/cbc.go:101 +0x26
github.com/hiromaily/go-gin-wrapper/vendor/github.com/hiromaily/golibs/cipher/encryption.(*Crypt).Decrypt(0xeeb760, 0xc4201ec540, 0x50, 0x51, 0x50, 0x51, 0x0)
        /go/src/github.com/hiromaily/go-gin-wrapper/vendor/github.com/hiromaily/golibs/cipher/encryption/encryption.go:134 +0xe3
github.com/hiromaily/go-gin-wrapper/vendor/github.com/hiromaily/golibs/cipher/encryption.(*Crypt).DecryptBase64(0xeeb760, 0xc4201ef8f0, 0x6c, 0x0, 0x4, 0xada880, 0xc42011ede0)
        /go/src/github.com/hiromaily/go-gin-wrapper/vendor/github.com/hiromaily/golibs/cipher/encryption/encryption.go:145 +0xa9
github.com/hiromaily/go-gin-wrapper/core/configs.Cipher()
        /go/src/github.com/hiromaily/go-gin-wrapper/core/configs/configs.go:375 +0x7f2
github.com/hiromaily/go-gin-wrapper/core/configs.New(0x7ffdfe196c7a, 0x17, 0x1)
        /go/src/github.com/hiromaily/go-gin-wrapper/core/configs/configs.go:347 +0x4f
main.initConf()
        /go/src/github.com/hiromaily/go-gin-wrapper/cmd/ginserver/main.go:73 +0x3e
main.setupMain()
        /go/src/github.com/hiromaily/go-gin-wrapper/cmd/ginserver/main.go:45 +0x26
main.main()
        /go/src/github.com/hiromaily/go-gin-wrapper/cmd/ginserver/main.go:373 +0x22

**Comment by hiromaily** [comment]
@safezpa 
Hi,  you seem to execute with docker.toml. that sample docker.toml file is supposed to be used as docker environment.
If you wanna execute this server locally, please use toml copied from settings.default.toml.
Thanks.

**Comment by safezpa** [comment]
I do use as docker environment. The error still occurs

**Comment by hiromaily** [comment]
I got it. Sorry I didn't care error handling for encryption.
For now, I set initial encryption using  https://github.com/hiromaily/golibs/blob/master/cipher/encryption/encryption.go
And it requires environment variables as below.
```
	key := os.Getenv("ENC_KEY")
	iv := os.Getenv("ENC_IV")
```
So you should set these on your .bashrc or something for environment variable for now.

**Comment by hiromaily** [comment]
Each variable requires 16 letters precisely.
This is just example on .zshrc.
```
export 'ENC_KEY=aaaaaaaaaabbbbbb'
export 'ENC_IV=ccccccccccdddddd'
```

**Comment by safezpa** [comment]
It works! Thank you.

**Comment by safezpa** [comment]
web-mongo container has something wrong.
I have checked the Dockerfile and the Makefile.
```
# Dcokerfile for Mongo

FROM mongo:3.4

ARG mongo_port=27017
ENV MONGO_PORT=$mongo_port
ENV ENC_KEY='xxxxxxxxxkeykey'
ENV ENC_IV='xxxxxxxxxxxxiviv'
RUN mkdir settings
WORKDIR /settings
COPY . .

```
Maybe the mongoinit in the Makefile should be like this:
```
mongoinit:
	#After running mongodb
	docker exec web-mongo mongo 127.0.0.1:$(MONGO_PORT)/admin --eval "var port = $(MONGO_PORT);" /settings/init.js
	docker exec web-mongo mongorestore -h 127.0.0.1:${MONGO_PORT} --db hiromaily /settings/dump/hiromaily

```

**Comment by hiromaily** [comment]
@safezpa 
Sorry for this inconvenience.
Updated vendor directory and `dcfirst` task in Makefile.
mongo command have to be executed while mongo container is running.
